- name: Deploy Redmine
  hosts: all
  roles:
    - role: mariadb
    - role: redmine
    - role: nginx
  tasks:
    - name: directory exists custom theme directory
      stat:
        path: /vagrant/src/theme
      register: result
    - name: create symlink theme directory
      file:
        src: /vagrant/src/theme
        dest: "{{ redmine_home }}/public/themes/custom_theme"
        state: link
      when: result.stat.exists
    - name: directory exists custom plugin directory
      stat:
        path: /vagrant/src/plugin
      register: result
    - name: create symlink plugin directory
      file:
        src: /vagrant/src/plugin
        dest: "{{ redmine_home }}/plugins/custom_plugin"
        state: link
      when: result.stat.exists
    - name: Finish display message
      debug:
        msg: "Let's Redmine!"
